version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: imc_db
      MYSQL_USER: imc_user
      MYSQL_PASSWORD: imc_pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  backend:
    build:
      context: ../Backend
      dockerfile: Dockerfile
    env_file:
      - ../Backend/.env
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn imc_backend.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - ../Backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - mysql
    restart: always

  frontend:
    build:
      context: ../Frontend/imc
      dockerfile: Dockerfile

    env_file:
      - ../Frontend/imc/.env
    volumes:
      - frontend_build:/frontend/dist

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/static
      - media_volume:/media
      - frontend_build:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot_www:/var/www/certbot
      - certbot_certs:/etc/letsencrypt
    depends_on:
      - backend
      - frontend
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_certs:/etc/letsencrypt
    command: >
      certonly --webroot
      --webroot-path=/var/www/certbot
      --email youremail@example.com
      --agree-tos
      --no-eff-email
      -d imcpune.in
      -d www.imcpune.in

volumes:
  mysql_data:
  frontend_build:
  static_volume:
  media_volume:
  certbot_www:
  certbot_certs:
